name: async_event_loader
description: Dart package to handle async events.
homepage: https://github.com/dokumanx/async_event_loader
repository: https://github.com/dokumanx/async_event_loader
issue_tracker: https://github.com/dokumanx/async_event_loader/issues
version: 0.0.1+1


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  rxdart: ^0.27.7
  async: ^2.11.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
